title: Abel Dawit # your name (or website title) here
logo: "ProfessionalPic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 7+ years of experience in data analytics, visualization and ML/AI and a BAS in Bioengineering from University of Pennsylvania. Currently a Manager in Client Solutions - Analytics Services (Pharma) at Kepler.
  <br><br>
  Proficient in Python, SQL, Tableau, Datorama, Matlab, Javascript, MS Office, Google Analytics (UA/GA4).
  <br><br>
  <a href="https://www.linkedin.com/in/abeldawit/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
  
  
  
  
  
  
  
  
